#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE="${ENV_FILE:-apps/api/.env}"

banner "Allegra Ship It — AWS Amplify + App Runner"

say "Vercel can stay as a preview. Ship It needs a live AWS URL."
say "This wizard walks the Console-only path from infra/README.md."
say "Submission artifacts (video, learning log, write-up) are intentionally left for the team."
confirm "Ready to start the AWS cutover?"

stage "1 · Confirm GitHub main is deployable"
say "App Runner and Amplify both build from GitHub. Uncommitted local work will not deploy."
step "Ensure the branch with the latest API/web work is merged (or selected) on the repo App Runner will watch."
open_url "https://github.com/ROSHINI-CLOUD/allegra"
pause "Press Enter when the deploy branch on GitHub includes the latest commits."

stage "2 · App Runner (API)"
say "Create the Express API service from the GitHub source directory apps/api."
open_url "https://console.aws.amazon.com/apprunner/home"
step "Create service → Source code repository → connect GitHub → this repo."
step "Source directory: apps/api · Runtime Node.js 20 · Build: npm ci && npm run build · Start: npm start · Port 8080."
step "Health check HTTP path: /api/health · Instance: 0.25 vCPU / 0.5 GB is enough for the hackathon."
step "Env (plaintext unless noted Secret): NODE_ENV=production, PORT=8080, AWS_REGION=<your region>,"
step "  ALLEGRA_ORIGIN=https://placeholder.local (update after Amplify),"
step "  JWT_SECRET (Secret), SAAVN_API_URL (Secret), GAANA_API_URL (Secret),"
step "  LRCLIB_API_URL=https://lrclib.net/api,"
step "  optional: CONVEX_URL, CONVEX_SERVER_SECRET, AI_PRIMARY=bedrock, AWS_* / DDB_TABLE_CACHE / S3_*."
ask APPRUNNER_URL "Paste the App Runner service URL (https://….awsapprunner.com, no trailing slash):"
write_env APPRUNNER_URL "$APPRUNNER_URL"
pause "curl $APPRUNNER_URL/api/health should return ok before continuing."

stage "3 · Amplify Hosting (web)"
say "Host the SPA on Amplify so Ship It has an AWS frontend URL."
open_url "https://console.aws.amazon.com/amplify/home"
step "Host web app → connect the same GitHub repo · app root apps/web."
step "Build: npm ci && npm run build · Output: dist."
step "Env: VITE_API_BASE_URL=$APPRUNNER_URL"
step "Add SPA rewrite: </^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|json|webp|mp3|mp4)$)([^.]+$)/> → /index.html (200)."
ask AMPLIFY_URL "Paste the Amplify app URL (https://….amplifyapp.com, no trailing slash):"
write_env AMPLIFY_URL "$AMPLIFY_URL"

stage "4 · Close the CORS loop"
say "The API origin allowlist must match the Amplify URL exactly."
open_url "https://console.aws.amazon.com/apprunner/home"
step "Edit the App Runner service → Configuration → Environment → set ALLEGRA_ORIGIN=$AMPLIFY_URL"
step "Redeploy the App Runner service."
write_env ALLEGRA_ORIGIN "$AMPLIFY_URL"
pause "Press Enter after App Runner finishes redeploying."

stage "5 · Live Gate 1 check"
say "On the Amplify URL (phone data if possible): search → play → scrub seek."
open_url "$AMPLIFY_URL"
step "In DevTools → Network, seeking should show 206 Partial Content on /api/stream/…"
confirm "Did search → play → seek work on the Amplify URL?"

stage "6 · README live URL"
say "Replace the preview line in README.md with the Amplify URL for judges."
step "Set README Live: $AMPLIFY_URL"
write_env VITE_API_BASE_URL "$APPRUNNER_URL"
note "Commit the README URL update on a small chore commit after this wizard."
pause "Press Enter when README shows the Amplify URL."

finish
note "Left for humans: demo video <3 min, write-up, LEARNING-LOG.md entries."
